apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS multidr;
    CREATE USER 'mysql'@'%' IDENTIFIED BY 'HelloDublin';
    GRANT ALL PRIVILEGES ON multidr.* TO 'mysql'@'%';
    FLUSH PRIVILEGES;
