apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: ye1234/multidrweb:20250714154642
        name: web-container
        ports:
         - containerPort: 80
           protocol: TCP
        workingDir: /var/www
        resources: {}
status: {}
